# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import kv_pb2 as kv__pb2


class KeyValueStoreStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
            '/KeyValueStore/Create',
            request_serializer=kv__pb2.CreateRequest.SerializeToString,
            response_deserializer=kv__pb2.CreateResponse.FromString,
        )
        self.Retrieve = channel.unary_unary(
            '/KeyValueStore/Retrieve',
            request_serializer=kv__pb2.RetrieveRequest.SerializeToString,
            response_deserializer=kv__pb2.RetrieveResponse.FromString,
        )
        self.Update = channel.unary_unary(
            '/KeyValueStore/Update',
            request_serializer=kv__pb2.UpdateRequest.SerializeToString,
            response_deserializer=kv__pb2.UpdateResponse.FromString,
        )
        self.Delete = channel.unary_unary(
            '/KeyValueStore/Delete',
            request_serializer=kv__pb2.DeleteRequest.SerializeToString,
            response_deserializer=kv__pb2.DeleteResponse.FromString,
        )


class KeyValueStoreServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def Create(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyValueStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Create': grpc.unary_unary_rpc_method_handler(
            servicer.Create,
            request_deserializer=kv__pb2.CreateRequest.FromString,
            response_serializer=kv__pb2.CreateResponse.SerializeToString,
        ),
        'Retrieve': grpc.unary_unary_rpc_method_handler(
            servicer.Retrieve,
            request_deserializer=kv__pb2.RetrieveRequest.FromString,
            response_serializer=kv__pb2.RetrieveResponse.SerializeToString,
        ),
        'Update': grpc.unary_unary_rpc_method_handler(
            servicer.Update,
            request_deserializer=kv__pb2.UpdateRequest.FromString,
            response_serializer=kv__pb2.UpdateResponse.SerializeToString,
        ),
        'Delete': grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=kv__pb2.DeleteRequest.FromString,
            response_serializer=kv__pb2.DeleteResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'KeyValueStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
